// Generated by CoffeeScript 1.3.2
(function() {
  var W, X, i, k, t;

  X = window;

  W = $(X);

  W.focus();

  i = new X.Game();

  k = {
    13: i.toggle,
    37: i.l,
    39: i.r,
    38: i.rotR,
    40: i.rotL,
    32: i.drop
  };

  W.keydown(function(e) {
    var f;
    f = k[e.which];
    if (f) {
      return f();
    }
  });

  t = [0, 0];

  W.bind("deviceorientation", function() {
    return t = [event.beta, event.gamma];
  });

  setInterval(function() {
    if (t[1] < -16) {
      i.l();
    }
    if (t[1] > 16) {
      i.r();
    }
    if (t[0] > 75) {
      return i.drop();
    }
  }, 400);

  W.bind("touchstart", function() {
    return i.rotR();
  });

}).call(this);
