// Generated by CoffeeScript 1.6.2
(function() {
  var a, e, ex, fs, t;

  e = require('express');

  t = require('./t.js');

  ex = require('child_process').exec;

  fs = require('fs');

  a = e();

  a.use(e.bodyParser());

  a.use(e["static"](__dirname));

  a.post('/h', function(req, res) {
    var b, g, s;

    b = req.body;
    if (b.n.match(/^\s*$/)) {
      return;
    }
    g = new t.Game();
    s = g.run(b);
    fs.appendFileSync('z.txt', s + "\t" + b.n + "\n");
    ex("sort -nr z.txt|head -n25>H");
    return res.send('');
  });

  a.listen(3000);

}).call(this);
