// Generated by CoffeeScript 1.3.2
(function() {
  var Game, PI, PJ, PL, PO, PS, PT, PZ, Piece, R, c, g, height, next, pieces, size, width,
    __defineProperty = function(clazz, key, value) {
  if (typeof clazz.__defineProperty == 'function') return clazz.__defineProperty(key, value);
  return clazz.prototype[key] = value;
},
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends =   function(child, parent) {
    if (typeof parent.__extend == 'function') return parent.__extend(child);
    for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } 
    function ctor() { this.constructor = child; } 
    ctor.prototype = parent.prototype; 
    child.prototype = new ctor; 
    child.__super__ = parent.prototype; 
    if (typeof parent.extended == 'function') parent.extended(child); 
    return child; 
};

  width = 10;

  height = 15;

  size = 30;

  $("#game").css("width", size * width);

  $("#game").css("height", size * height);

  $("#next").css("width", size * 4);

  $("#next").css("height", size * 4);

  R = Raphael;

  c = R("game", "100%", "100%");

  next = R("next", "100%", "100%");

  Piece = (function() {

    function Piece() {
      this.remove = __bind(this.remove, this);

      this.bounds = __bind(this.bounds, this);

      this.clone = __bind(this.clone, this);

      this.down = __bind(this.down, this);

      this.r = __bind(this.r, this);

      this.l = __bind(this.l, this);

      this.draw = __bind(this.draw, this);

      this.rotL = __bind(this.rotL, this);

      this.rotR = __bind(this.rotR, this);
      this.shape = this.bshape;
      this.blocks = [];
      this.xbase = 0;
      this.ybase = 0;
    }

    __defineProperty(Piece,  "rotR", function() {
      var col, n, r, row, _i, _j, _ref, _ref1;
      n = [];
      for (row = _i = 0, _ref = this.shape[0].length - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; row = 0 <= _ref ? ++_i : --_i) {
        r = [];
        for (col = _j = 0, _ref1 = this.shape.length - 1; 0 <= _ref1 ? _j <= _ref1 : _j >= _ref1; col = 0 <= _ref1 ? ++_j : --_j) {
          r.push(this.shape[this.shape.length - col - 1][row]);
        }
        n.push(r);
      }
      this.shape = n;
      return this;
    });

    __defineProperty(Piece,  "rotL", function() {
      var x, _i;
      for (x = _i = 0; _i <= 2; x = ++_i) {
        this.rotR();
      }
      return this;
    });

    __defineProperty(Piece,  "draw", function(c) {
      var b, col, row, x, y, _i, _len, _ref, _ref1, _results;
      this.xbase = Math.max(0, this.xbase);
      this.xbase = Math.min(width - this.shape[0].length, this.xbase);
      _ref = this.blocks;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        b = _ref[_i];
        b.remove();
      }
      _ref1 = this.shape;
      _results = [];
      for (y in _ref1) {
        row = _ref1[y];
        _results.push((function() {
          var _results1;
          _results1 = [];
          for (x in row) {
            col = row[x];
            if (col === 1) {
              x = 1.0 * x;
              y = 1.0 * y;
              b = c.rect((this.xbase + x) * size, (+this.ybase + y) * size, size, size);
              b.attr("fill", this.color);
              b.attr("stroke", "#000");
              _results1.push(this.blocks.push(b));
            } else {
              _results1.push(void 0);
            }
          }
          return _results1;
        }).call(this));
      }
      return _results;
    });

    __defineProperty(Piece,  "l", function() {
      this.xbase -= 1;
      return this;
    });

    __defineProperty(Piece,  "r", function() {
      this.xbase += 1;
      return this;
    });

    __defineProperty(Piece,  "down", function() {
      this.ybase += 1;
      return this;
    });

    __defineProperty(Piece,  "clone", function() {
      var p;
      p = new this.constructor();
      p.xbase = this.xbase;
      p.ybase = this.ybase;
      p.shape = this.shape;
      return p;
    });

    __defineProperty(Piece,  "bounds", function() {
      var ba, col, row, x, y, _ref;
      ba = [];
      _ref = this.shape;
      for (y in _ref) {
        row = _ref[y];
        for (x in row) {
          col = row[x];
          if (col === 1) {
            ba.push([x * 1.0 + this.xbase, y * 1.0 + this.ybase]);
          }
        }
      }
      return ba;
    });

    __defineProperty(Piece,  "remove", function() {
      var b, _i, _len, _ref, _results;
      _ref = this.blocks;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        b = _ref[_i];
        _results.push(b.remove());
      }
      return _results;
    });

    return Piece;

  })();

  PI = (function(_super) {

    function PI() {
      return PI.__super__.constructor.apply(this, arguments);
    }

    PI = __extends(PI, _super);

    __defineProperty(PI,  "bshape", [[1, 1, 1, 1]]);

    __defineProperty(PI,  "color", 'cyan');

    return PI;

  })(Piece);

  PJ = (function(_super) {

    function PJ() {
      return PJ.__super__.constructor.apply(this, arguments);
    }

    PJ = __extends(PJ, _super);

    __defineProperty(PJ,  "bshape", [[1, 1, 1], [0, 0, 1]]);

    __defineProperty(PJ,  "color", 'blue');

    return PJ;

  })(Piece);

  PL = (function(_super) {

    function PL() {
      return PL.__super__.constructor.apply(this, arguments);
    }

    PL = __extends(PL, _super);

    __defineProperty(PL,  "bshape", [[1, 1, 1], [1, 0, 0]]);

    __defineProperty(PL,  "color", 'orange');

    return PL;

  })(Piece);

  PO = (function(_super) {

    function PO() {
      return PO.__super__.constructor.apply(this, arguments);
    }

    PO = __extends(PO, _super);

    __defineProperty(PO,  "bshape", [[1, 1], [1, 1]]);

    __defineProperty(PO,  "color", 'yellow');

    return PO;

  })(Piece);

  PS = (function(_super) {

    function PS() {
      return PS.__super__.constructor.apply(this, arguments);
    }

    PS = __extends(PS, _super);

    __defineProperty(PS,  "bshape", [[0, 1, 1], [1, 1, 0]]);

    __defineProperty(PS,  "color", 'green');

    return PS;

  })(Piece);

  PZ = (function(_super) {

    function PZ() {
      return PZ.__super__.constructor.apply(this, arguments);
    }

    PZ = __extends(PZ, _super);

    __defineProperty(PZ,  "bshape", [[1, 1, 0], [0, 1, 1]]);

    __defineProperty(PZ,  "color", 'purple');

    return PZ;

  })(Piece);

  PT = (function(_super) {

    function PT() {
      return PT.__super__.constructor.apply(this, arguments);
    }

    PT = __extends(PT, _super);

    __defineProperty(PT,  "bshape", [[0, 1, 0], [1, 1, 1]]);

    __defineProperty(PT,  "color", 'red');

    return PT;

  })(Piece);

  pieces = [PI, PT, PO, PJ, PL, PS, PZ];

  Game = (function() {

    function Game() {
      this.draw = __bind(this.draw, this);

      this.gameover = __bind(this.gameover, this);

      this.persist = __bind(this.persist, this);

      this.rotR = __bind(this.rotR, this);

      this.rotL = __bind(this.rotL, this);

      this.r = __bind(this.r, this);

      this.l = __bind(this.l, this);

      this.drop = __bind(this.drop, this);

      this.tick = __bind(this.tick, this);

      this.check = __bind(this.check, this);

      this.init = __bind(this.init, this);
      this.init();
      this.tick();
      setInterval(this.tick, 1000);
    }

    __defineProperty(Game,  "init", function() {
      var b, col, row, _i, _j, _k, _len, _ref, _ref1, _ref2;
      if (this.blocks) {
        _ref = this.blocks;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          b = _ref[_i];
          b.remove();
        }
      }
      this.score = 0;
      this.blocks = [];
      if (this.piece) {
        this.piece.remove();
      }
      this.piece = null;
      if (this.next) {
        this.next.remove();
      }
      this.next = null;
      this.matrix = [];
      for (row = _j = 0, _ref1 = height - 1; 0 <= _ref1 ? _j <= _ref1 : _j >= _ref1; row = 0 <= _ref1 ? ++_j : --_j) {
        this.matrix[row] = [];
        for (col = _k = 0, _ref2 = width - 1; 0 <= _ref2 ? _k <= _ref2 : _k >= _ref2; col = 0 <= _ref2 ? ++_k : --_k) {
          this.matrix[row][col] = null;
        }
      }
      this.tick();
      return this.draw();
    });

    __defineProperty(Game,  "check", function(p) {
      var b, _i, _len, _ref;
      _ref = p.bounds();
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        b = _ref[_i];
        if (b[1] >= height) {
          return false;
        }
        if (this.matrix[b[1]][b[0]] !== null) {
          return false;
        }
      }
      return true;
    });

    __defineProperty(Game,  "tick", function() {
      if (this.piece !== null) {
        if (this.check(this.piece.clone().down())) {
          this.piece.down();
        } else {
          this.persist(this.piece);
          this.piece.remove();
          this.draw();
          this.piece = null;
        }
      }
      if (this.piece === null) {
        this.piece = this.next;
        if (this.piece !== null && !this.check(this.piece)) {
          return this.gameover();
        }
        this.next = new pieces[Math.floor(Math.random() * pieces.length)]();
      }
      if (this.piece) {
        this.piece.draw(c);
      }
      return this.next.draw(next);
    });

    __defineProperty(Game,  "drop", function() {
      var _results;
      this.tick();
      _results = [];
      while (this.piece.ybase !== 0) {
        _results.push(this.tick());
      }
      return _results;
    });

    __defineProperty(Game,  "l", function() {
      if (this.check(this.piece.clone().l())) {
        this.piece.l();
        return this.piece.draw(c);
      }
    });

    __defineProperty(Game,  "r", function() {
      if (this.check(this.piece.clone().r())) {
        this.piece.r();
        return this.piece.draw(c);
      }
    });

    __defineProperty(Game,  "rotL", function() {
      if (this.check(this.piece.clone().rotL())) {
        this.piece.rotL();
        return this.piece.draw(c);
      }
    });

    __defineProperty(Game,  "rotR", function() {
      if (this.check(this.piece.clone().rotR())) {
        this.piece.rotR();
        return this.piece.draw(c);
      }
    });

    __defineProperty(Game,  "persist", function(p) {
      var coord, _i, _len, _ref, _results;
      _ref = p.bounds();
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        coord = _ref[_i];
        _results.push(this.matrix[coord[1]][coord[0]] = p.color);
      }
      return _results;
    });

    __defineProperty(Game,  "gameover", function() {
      alert("game over");
      return this.init();
    });

    __defineProperty(Game,  "draw", function() {
      var b, col, full, i, row, rowsKilled, x, y, _i, _j, _len, _ref, _ref1, _ref2, _results;
      _ref = this.blocks;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        b = _ref[_i];
        b.remove();
      }
      rowsKilled = 0;
      _ref1 = this.matrix;
      for (y in _ref1) {
        row = _ref1[y];
        full = true;
        for (x in row) {
          col = row[x];
          if (col === null) {
            full = false;
          }
        }
        if (full) {
          rowsKilled += 1;
          this.matrix.splice(y, 1);
          this.matrix.unshift([]);
          for (i = _j = 1; 1 <= width ? _j <= width : _j >= width; i = 1 <= width ? ++_j : --_j) {
            this.matrix[0].push(null);
          }
        }
      }
      if (rowsKilled > 0) {
        this.score += Math.pow(2, rowsKilled - 1) * 1000;
      }
      $("#score").html(this.score);
      _ref2 = this.matrix;
      _results = [];
      for (y in _ref2) {
        row = _ref2[y];
        _results.push((function() {
          var _results1;
          _results1 = [];
          for (x in row) {
            col = row[x];
            if (col === null) {
              continue;
            }
            b = c.rect((x * 1.0) * size, (y * 1.0) * size, size, size);
            b.attr("fill", col);
            b.attr("stroke", "#000");
            _results1.push(this.blocks.push(b));
          }
          return _results1;
        }).call(this));
      }
      return _results;
    });

    return Game;

  })();

  g = new Game();

  $(document).keydown(function(e) {
    switch (e.which) {
      case 37:
        return g.l();
      case 39:
        return g.r();
      case 38:
        return g.rotR();
      case 40:
        return g.rotL();
      case 32:
        return g.drop();
    }
  });

}).call(this);
